// SAS-022 — Zod schema for the fixture JSON format documented in docs/FIXTURES.md §4.
//
// Two deliberate extensions beyond the documented shape (both noted in FIXTURES.md itself):
//   - `runConfig` — the literal RunConfig used to produce the run, alongside the smaller
//     display-only `config` block. calibrate.py and the MAE gate need the full config (memory
//     fractions, row counts, query shape) to reconstruct costs, not just 4 display fields.
//   - `synthetic` — true for a fixture generated by generate-synthetic.ts rather than captured
//     from a real cluster. `resolve.ts` excludes synthetic fixtures from its snapping index, so
//     a synthetic fixture can never make the UI show `MEASURED`.
// Each task also carries `rows` (fixtures-schema-only, not part of TaskResult) — calibrate.py's
// per-task regression needs a row count for the computeMs/sortMs terms; the loader strips it
// before building a RunResult.
//
// Every byte/ms field is passed through @sas/sim's branded constructors via `.transform()` —
// never a raw cast — so a fixture, once validated, is exactly as trustworthy as simulator output.
import { z } from 'zod';
import { asBytes, asSimMs } from '@sas/sim';
import type { AqeRewrite, PlanNode, RunConfig } from '@sas/sim';

const PlanNodeKindSchema = z.enum([
  'Scan',
  'Exchange',
  'BroadcastExchange',
  'Sort',
  'Aggregate',
  'Project',
  'BroadcastHashJoin',
  'ShuffledHashJoin',
  'SortMergeJoin',
]);

// z.lazy is required for a recursive shape; the explicit z.ZodType<PlanNode> annotation is
// zod's documented pattern for typing a recursive schema against an existing interface.
export const PlanNodeSchema: z.ZodType<PlanNode> = z.lazy(() =>
  z.object({
    id: z.number(),
    kind: PlanNodeKindSchema,
    children: z.array(PlanNodeSchema),
    stageId: z.number(),
    estimatedSizeBytes: z.number().transform(asBytes).optional(),
    actualSizeBytes: z.number().transform(asBytes).optional(),
    partitionCount: z.number().optional(),
  })
);

const AqeRewriteSchema: z.ZodType<AqeRewrite> = z.object({
  rule: z.enum(['optimizeSkewedJoin', 'coalesceShufflePartitions', 'dynamicJoinSelection']),
  atMs: z.number().transform(asSimMs),
  producingStageId: z.number(),
  description: z.string(),
  before: PlanNodeSchema,
  after: PlanNodeSchema,
});

const QuerySpecSchema: z.ZodType<RunConfig['query']> = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('aggregate') }),
  z.object({
    kind: z.literal('join'),
    joinType: z.enum(['inner', 'left']),
    other: z.object({ rows: z.number(), bytesPerRow: z.number() }),
    broadcastHint: z.boolean().optional(),
    estimateErrorFactor: z.number().optional(),
  }),
  z.object({ kind: z.literal('window'), partitionByKeyCardinality: z.number() }),
]);

/** Mirrors `RunConfig` field-for-field (docs/SIMULATOR_SPEC.md §1) — the D1 schema extension. */
export const RunConfigSchema: z.ZodType<RunConfig> = z.object({
  cluster: z.object({
    executors: z.number(),
    coresPerExecutor: z.number(),
    executorMemoryMiB: z.number(),
    memoryFraction: z.number(),
    storageFraction: z.number(),
  }),
  sql: z.object({
    shufflePartitions: z.number(),
    autoBroadcastJoinThresholdMiB: z.number(),
    adaptive: z.object({
      enabled: z.boolean(),
      advisoryPartitionSizeMiB: z.number(),
      coalescePartitions: z.boolean(),
      skewJoinEnabled: z.boolean(),
      skewedPartitionFactor: z.number(),
      skewedPartitionThresholdMiB: z.number(),
    }),
  }),
  data: z.object({
    rows: z.number(),
    keyCardinality: z.number(),
    zipfAlpha: z.number(),
    nullFraction: z.number(),
    bytesPerRow: z.number(),
    saltFactor: z.number(),
  }),
  query: QuerySpecSchema,
});

const EnvironmentSchema = z.object({
  sparkVersion: z.string(),
  runtime: z.string(),
  nodes: z.number(),
  nodeType: z.string(),
  executorMemoryMiB: z.number(),
  coresPerExecutor: z.number(),
});

/** The small display block shown in the UI's config-diff — see docs/FIXTURES.md §4. */
const FixtureConfigSchema = z.object({
  zipfAlpha: z.number(),
  saltFactor: z.number(),
  shufflePartitions: z.number(),
  aqe: z.boolean(),
});

const StageResultSchema = z.object({
  stageId: z.number(),
  planNodeId: z.number(),
  taskIds: z.array(z.number()),
  launchMs: z.number().transform(asSimMs),
  finishMs: z.number().transform(asSimMs),
  status: z.enum(['ok', 'failed']),
  partitionBytes: z.array(z.number().transform(asBytes)),
});

/** TaskResult plus the fixtures-only `rows` field (D2) — `loader.ts` strips it. */
const FixtureTaskSchema = z.object({
  taskId: z.number(),
  stageId: z.number(),
  slot: z.number(),
  partitionId: z.number(),
  launchMs: z.number().transform(asSimMs),
  finishMs: z.number().transform(asSimMs),
  inputBytes: z.number().transform(asBytes),
  shuffleReadBytes: z.number().transform(asBytes),
  shuffleWriteBytes: z.number().transform(asBytes),
  fetchWaitMs: z.number().transform(asSimMs),
  gcMs: z.number().transform(asSimMs),
  memorySpilledBytes: z.number().transform(asBytes),
  diskSpilledBytes: z.number().transform(asBytes),
  peakExecutionMemoryBytes: z.number().transform(asBytes),
  status: z.enum(['ok', 'spilled', 'oom']),
  /** Fixtures-schema-only extension — see file header. */
  rows: z.number(),
});

export const FixtureSchema = z.object({
  id: z.string(),
  schemaVersion: z.literal(1),
  captured: z.string(),
  environment: EnvironmentSchema,
  config: FixtureConfigSchema,
  /** D1 — the full config, alongside the smaller display-only `config` block above. */
  runConfig: RunConfigSchema,
  pairedWith: z.string().optional(),
  notes: z.string(),
  /** D3 — true for a generate-synthetic.ts fixture. `resolve.ts` excludes these from snapping. */
  synthetic: z.boolean().default(false),
  sampling: z.object({
    ratio: z.number(),
    /** Only present when §3's downsampling rule actually fired. */
    samplingRatio: z.number().optional(),
  }),
  stages: z.array(StageResultSchema),
  tasks: z.array(FixtureTaskSchema),
  // Matches RunResult['plan'] exactly, resolving FIXTURES.md's vaguer sketch into the concrete
  // shape needed so a fixture can fully substitute for a measured RunResult.
  plan: z.object({
    initial: PlanNodeSchema,
    final: PlanNodeSchema,
    rewrites: z.array(AqeRewriteSchema),
  }),
});

export type ValidatedFixture = z.infer<typeof FixtureSchema>;
export type ValidatedFixtureTask = z.infer<typeof FixtureTaskSchema>;

/**
 * Validates a raw JSON value against the fixture schema. Throws a descriptive error (not a bare
 * ZodError) on failure — "a fixture that fails validation fails CI" (docs/FIXTURES.md §4).
 */
export function validateFixture(json: unknown): ValidatedFixture {
  const result = FixtureSchema.safeParse(json);
  if (!result.success) {
    const id = typeof json === 'object' && json !== null && 'id' in json ? String((json as { id: unknown }).id) : 'unknown';
    const issues = result.error.issues.map((issue) => `  ${issue.path.join('.') || '(root)'}: ${issue.message}`).join('\n');
    throw new Error(`Fixture "${id}" failed schema validation:\n${issues}`);
  }
  return result.data;
}
