// GENERATED by tools/capture/calibrate.py — do not edit by hand.
// Fitted against 15 SYNTHETIC runs (packages/sim simulate() + injected
// jitter) — NOT real Spark captures. Real calibration happens after the SAS-020/023/024
// real-cluster follow-up.
// Residual: mean absolute error 0.9 % on stage wall clock (n=4614, R² 1.00).

export const DESERIALIZE_MS_PER_TASK = 1.84969;
export const READ_THROUGHPUT_MBPS = 398.842;
export const CPU_NS_PER_ROW = 50.1451;
export const SORT_NS_PER_ROW_LOG = 26.2233;
export const SHUFFLE_WRITE_THROUGHPUT_MBPS = 149.566;
export const NETWORK_BANDWIDTH_MBPS = 34.4737;
export const SERIALIZATION_RATIO = 0.34923;
export const SPILL_WRITE_THROUGHPUT_MBPS = 198.175;
export const SPILL_READ_THROUGHPUT_MBPS = 247.719;
export const SPILL_MERGE_COST_MS = 4.34835;
export const OOM_THRESHOLD_RATIO = 1.8;
export const GC_BASE_MS = 2.04683;
